name: application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.4.0
  image_picker: ^1.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  supabase_flutter: ^2.9.1
  geocoding: ^2.1.0
  flutter_dotenv: ^5.1.0
  package_info_plus: ^8.3.0
  intl: ^0.20.2
  google_sign_in: ^6.1.5
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
